[tool.poetry]
name = "edgar-tool"
version = "1.3.3"
description = "Search and retrieve corporate and financial data from the United States Securities and Exchange Commission (SEC)."
authors = ["Bellingcat"]
license = "GNU General Public License v3 (GPLv3)"
readme = "README.md"
repository = "https://github.com/bellingcat/EDGAR"
classifiers = [
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Office/Business :: Financial",
]
keywords=["scraper", "edgar", "finance", "sec"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/bellingcat/EDGAR/issues"

[tool.poetry.scripts]
edgar-tool = "edgar_tool.main:main_entrypoint"

[tool.poetry.dependencies]
python = "^3.9"
tenacity = "^8.2"
fire = "^0.5"
jsonlines = "^4.0"
requests = "^2.31"
xmltodict = "^0.13"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
tox = "^4.16.0"
pytest = "^8.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
